### PR TITLE
intialized cypress and node js json file.

### PR DESCRIPTION
**Pull request by nimapourjafar**

### CODE REVIEW

**Comment by l2silver** [comment]
Looks like node_modules folder was added. We should gitignore that folder.

**Comment by l2silver** [comment]
Youve also got to clear the git cache to remove the node modules that were already committed

`git rm -R --cached node_modules`

**Comment by nimapourjafar** [comment]
hey silver, I'm not sure if I cleared the git cache. I ran the command in
my terminal while I was in the e2e folder and committed it to my branch,
but I don't see the commit in my branch history. It may be something on my
end, but I'd rather make sure the problem gets resolved on all ends.

**Comment by l2silver** [comment]
@nimapourjafar try looking at this. I don't know if you can see, but you're committing over 5000 files right now, so you'll know you've done it right when that file total drops to only the cypress specific files. ~5-15 I believe. Check out the stackoverflow below. And make sure to push your code afterwards.

https://stackoverflow.com/questions/50675829/remove-node-modules-from-git-in-vscode

And don't forget to sign the CLA ^^

**Comment by nimapourjafar** [comment]
Hey, silver. Just want to clarify some things.
1. I should have a separate gitignore file in the e2e folder and have
"node_modules" in it
2. When I run the command to clear the git cache, the node_modules folder
in e2e should only have cypress in it.

Thanks,
Nima.

**Review by l2silver — APPROVED** [review]

**Pull request merged**
