### PR TITLE
feature/40

### PR DESCRIPTION
**Pull request by OksanaSam**
#40 
Description

Make it so that when some visits the base url for the app, they see the login page.

- Redirecting to signIn page by default if there is no user - mock user for now

### CODE REVIEW

**Review by l2silver — CHANGES_REQUESTED** [review]
This is perfect! Do you think you could include a test to confirm this behaviour?

- [ ] write test

**Comment by OksanaSam** [comment]
> This is perfect! Do you think you could include a test to confirm this behaviour?
> 
> * [ ]  write test

Yes, will do!

**Comment by l2silver** [comment]
@holt16589 Hey Kevin, can you finish this ticket by writing tests for these changes? Thanks

**Comment by holt16589** [comment]
> @holt16589 Hey Kevin, can you finish this ticket by writing tests for these changes? Thanks

Hey Leigh, let me know if this works!

My initial approach was to mock getUser to test both cases (i.e. null vs defined) but I had some challenges. I'm happy to revise/add an additional test if needed.

**Review by l2silver — APPROVED** [review]
Thanks @OksanaSam and @holt16589 .

**Pull request merged**
