### PR TITLE
Feature/255 create api call for create Org

### PR DESCRIPTION
**Pull request by ynynl**
Done: creat 2 calls of POST request for creating organization and account manager.

Issues: 
* The user api is not working (see the screenshot). 
* The frontend only has the email field and no username field, while the backend api is on the opposite. For now, I use the email input as the username to send to the backend. 

Request: 
`curl -X POST "https://vt-volunteer-drivers-app.herokuapp.com/users/" -H  "accept: application/json" -H  "authorization: Basic b3JnYWRtaW5AdnQuY2E6b3JnYWRtaW5AdnQuY2E=" -H  "Content-Type: application/json" -H  "X-CSRFToken: JXd1TDZbyUhicMVzCJ2aWW5rVu3VxfgNSg8P9OytPYpQbeTkXSqz7f09rfshLWi7" -d "{  \"username\": \"ununun\",  \"password\": \"password\",  \"organization_id\": 20,  \"first_name\": \"fn\",  \"last_name\": \"ln\"}"`

Response
image

### CODE REVIEW

**Comment by l2silver** [comment]
Ah you're absolutely right. For some reason django is ignoring the username and password field, which means that the first time you create a user, those fields are empty. the next time you try to create a user, it sees that you're trying to create a user without a username, but since there's already a user without a username, it throws that horrible error.

**Comment by l2silver** [comment]
I'm going to work on a django solution to this right away.

**Comment by l2silver** [comment]
@ynynl  can you take a look at this commit: https://github.com/diglit/volunteer-toronto-volunteer-drivers-app/pull/286/commits/57ae32843db3c6cb2890838aab9bf11dc6567748

**Review by l2silver — APPROVED** [review]
Excellent Work!

**Comment by ynynl** [comment]
> @ynynl  can you take a look at this commit: https://github.com/diglit/volunteer-toronto-volunteer-drivers-app/pull/286/commits/57ae32843db3c6cb2890838aab9bf11dc6567748

Thank you for fixing those mistakes!

**Pull request merged**
