### PR TITLE
Feature/266

### PR DESCRIPTION
**Pull request by andreipakemp**
Add simple tests to verify that the endpoint for creating organizations works and returns the id of the newly created organization

### CODE REVIEW

**Review by l2silver — APPROVED** [review]
AWESOME!

**Comment by l2silver** [comment]
@cemgurbey Not sure if this will help with writing tests

**Comment by cemgurbey** [comment]
@l2silver yes, it is very useful for my part as well. Thank you @andreipakemp !

**Comment by andreipakemp** [comment]
No problem, Glad I could help!

**Pull request merged**
